language: go

go:
  - 1.9

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

sudo: required

services:
  - docker

install:
  - make dependencies

script:
  - make test-coverage
  - make codecov

before_deploy:
  - make packages

jobs:
  include:
    - stage: deploy
      if: tag IS present
      services: docker
      install: true
      before_script: true
      script: ci-deploy
